version: "3"
services:
  consumer:
    image: spring-docker-app
    ports:
      - "8000:8080"
    networks:
      - consumer-producer
    depends_on:
      - producer

  producer:
    image: spring-docker-compose
    ports:
      - "8080:8080"
    networks:
      - consumer-producer

networks:
  consumer-producer: